name: dart_crypto
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  pointycastle: ^3.6.2	
  bs58check: ^1.0.2
  convert: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.0.6
  freezed: ^0.14.2
  json_serializable: ^4.1.4
