name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: stable
    - name: Get dependencies
      run: flutter pub get
    - name: Run tests
      run: dart test
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test/test_results.xml